### ISSUE TITLE
Editing a server resets TLS and sets invalid server name

### ISSUE THREAD

**Issue by ukcb** [Nordaaker/convos#344]
A small problem when editing a server. I have defined a server any-server:6697, a nick, TLS is On, username and password; state is connected. If you delete the username and save the settings, TLS will jump to Off and the servername will change to the default server (from CONVOS_DEFAULT_SERVER).
Can you understand that? I'm using the current git master.

**Comment by jhthorsen** [comment]
I cannot reproduce this issue. Can you do a screen capture or send attach some screenshots?

**Comment by ukcb** [comment]
A small video. You can also see that the automatic connection to TLS does not work.

[video.zip](https://github.com/Nordaaker/convos/files/971615/video.zip)

**Comment by jhthorsen** [comment]
I got the video now. It's really strange...

I don't have time to look at it now, but will check it out later this week.

(Delete the video if you like)

**Comment by jhthorsen** [comment]
I think "TLS will jump to Off and the servername will change to the default server" was fixed in 0.99_35 and the TLS detection is for sure fixed in the commit above, 58a119e.

Sorry for taking so long.

**Comment by ukcb** [comment]
The automatic TLS connection works but there is still a problem with editing. See new video. [video.zip](https://github.com/Nordaaker/convos/files/990377/video.zip)

**Comment by jhthorsen** [comment]
I cannot reproduce what you are showing me... Which settings do you start Convos with? (config file or list of environment variables)

**Comment by ukcb** [comment]
I have no config file, everything is controlled by ENV variables

<pre>
# grep -v '^#' /var/www/convos/environment.conf
CONVOS_BACKEND="Convos::Core::Backend::File"
CONVOS_CONNECT_DELAY="3"
CONVOS_CONTACT="mailto:root@localhost"
CONVOS_DEFAULT_SERVER="localhost:6697"
CONVOS_HOME="/var/www/convos"
CONVOS_INVITE_CODE="s3cret"
CONVOS_LOG_FILE=/var/www/convos/convos.log
CONVOS_ORGANIZATION_NAME="Example"
CONVOS_ORGANIZATION_URL="http://example.org"
CONVOS_SECRETS="super,duper,secret"
CONVOS_SECURE_COOKIES="1"
MOJO_LISTEN="http://127.0.0.1:3001"
MOJO_REVERSE_PROXY="1"

# git show --oneline -s HEAD
0d1e75d Add note about TLS/SSL when creating a connection, closes #341
</pre>

**Comment by ukcb** [comment]
One more thing: After creating the connection, there is no &tls=? in the connection.json.
If I only save the connection is &tls=0 in the config.
Only when I save again stands there &tls=1
A little confusing.

**Comment by jhthorsen** [comment]
I tried with you exact config now, except CONVOS_SECURE_COOKIES and MOJO_REVERSE_PROXY, since I'm running the server directly on localhost and still can't reproduce the issues.

No "tls" in the connection string means "autodetect", while setting "tls=0" or "tls=1" means tls should be disabled/enabled.

You could try to install some extra modules and see if you can get the test suite to fail:

```
./script/convos install --develop
./script/convos test
TEST_SELENIUM=1 ./script/convos test t/selenium-*t
```

Remember to pull in the changes first, since I just added some new "develop" dependencies. The most important test is probably:

```
TEST_SELENIUM=1 ./script/convos test t/selenium-settings.t
```

Also note that config.t and version.t will probably fail.

**Comment by jhthorsen** [comment]
Oh... And the selenium tests require some optional packages:

```
# osx
brew install chromedriver
# ubuntu/debian
sudo apt-get install chromium-chromedriver
sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver # Not sure if this is really needed
```

**Comment by ukcb** [comment]
I have run the test, I hope it helps

<pre>
etchbox:/home/local/convos# ls -l /usr/bin/chromedriver 
lrwxrwxrwx 1 root root 30 Mai 11 16:34 /usr/bin/chromedriver -> /usr/lib/chromium/chromedriver
etchbox:/home/local/convos# ls -l /usr/lib/chromium/chromedriver
-rwxr-xr-x 1 root root 8334456 Mär 13 00:20 /usr/lib/chromium/chromedriver

etchbox:/home/local/convos# ./script/convos test                                              
[Thu May 11 16:40:27 2017] [info] CONVOS_HOME="/root/.local/share/convos" # https://convos.by/doc/config.html#convos_home"
[Thu May 11 16:40:27 2017] [info] CONVOS_INVITE_CODE="2953e94daa75a4fc00d2f2bf7563f750" # https://convos.by/doc/config.html#convos_invite_code
Running tests from "/home/local/convos/script/../t".
/home/local/convos/script/../t/00-basic.t ....................... ok     
/home/local/convos/script/../t/backend-file-basic.t ............. ok    
/home/local/convos/script/../t/backend-file-messages.t .......... ok    
/home/local/convos/script/../t/backend.t ........................ ok    
/home/local/convos/script/../t/config.t ......................... 1/? 
#   Failed test 'generated invite_code'
#   at /home/local/convos/script/../t/config.t line 18.
#                   undef
#     doesn't match '(?^:^\w{32}$)'
/home/local/convos/script/../t/config.t ......................... 20/? # Looks like you failed 1 test of 30.
/home/local/convos/script/../t/config.t ......................... Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/30 subtests 
/home/local/convos/script/../t/connection.t ..................... ok   
/home/local/convos/script/../t/irc-basic.t ...................... ok    
/home/local/convos/script/../t/irc-connect.t .................... 1/? [test.user@example.com/irc-localhost] connect(irc.example.com) == SSL connect attempt failed error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
[test.user@example.com/irc-localhost] connect(irc.example.com) == SSL connect attempt failed error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
[test.user@example.com/irc-localhost] connect(irc.example.com) == IO::Socket::SSL 1.94+ required for TLS support
[test.user@example.com/irc-localhost] connect(irc.example.com) == IO::Socket::SSL 1.94+ required for TLS support
/home/local/convos/script/../t/irc-connect.t .................... ok    
/home/local/convos/script/../t/irc-message.t .................... [superman@example.com/irc-localhost] connect(127.0.0.1:39673) == SSL connect attempt failed error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol

/home/local/convos/script/../t/irc-message.t .................... ok    
/home/local/convos/script/../t/irc-on-connect.t ................. ok   
/home/local/convos/script/../t/irc-real-servers.t ............... skipped: TEST_NETWORKS=all is not set
/home/local/convos/script/../t/irc-send.t ....................... ok    
/home/local/convos/script/../t/irc-steal-nick.t ................. ok    
/home/local/convos/script/../t/log.t ............................ # CONVOS_LOG_FILE=/tmp/D9jFydZ1uy
/home/local/convos/script/../t/log.t ............................ ok   
/home/local/convos/script/../t/plugin-share-dialog.t ............ ok    
/home/local/convos/script/../t/production-resources.t ........... 1/? [Thu May 11 16:40:40 2017] [error] Test 500 page at /home/local/convos/script/../lib/Convos.pm line 71.

/home/local/convos/script/../t/production-resources.t ........... ok    
/home/local/convos/script/../t/selenium-basic.t ................. skipped: TEST_SELENIUM=1
/home/local/convos/script/../t/selenium-hide.t .................. skipped: TEST_SELENIUM=1
/home/local/convos/script/../t/selenium-highlight.t ............. skipped: TEST_SELENIUM=1
/home/local/convos/script/../t/selenium-nick-change.t ........... skipped: TEST_SELENIUM=1
/home/local/convos/script/../t/selenium-register-forced.t ....... skipped: TEST_SELENIUM=1
/home/local/convos/script/../t/selenium-register-non-default.t .. skipped: TEST_SELENIUM=1
/home/local/convos/script/../t/selenium-register.t .............. skipped: TEST_SELENIUM=1
/home/local/convos/script/../t/selenium-responsive.t ............ skipped: TEST_SELENIUM=1
/home/local/convos/script/../t/selenium-settings.t .............. skipped: TEST_SELENIUM=1
/home/local/convos/script/../t/selenium-url.t ................... skipped: TEST_SELENIUM=1
/home/local/convos/script/../t/start.t .......................... ok   
/home/local/convos/script/../t/user.t ........................... ok    
/home/local/convos/script/../t/version.t ........................ 1/? 
#   Failed test 'correct version in Convos.pm code'
#   at /home/local/convos/script/../t/version.t line 14.
#          got: '0.99_35'
#     expected: '0.99_36'

#   Failed test 'correct version in Convos.pm pod'
#   at /home/local/convos/script/../t/version.t line 15.
#          got: '0.99_35'
#     expected: '0.99_36'

#   Failed test 'correct version in snap/snapcraft.yaml'
#   at /home/local/convos/script/../t/version.t line 18.
#          got: '0.99.35'
#     expected: '0.99.36'
# Looks like you failed 3 tests of 3.
/home/local/convos/script/../t/version.t ........................ Dubious, test returned 3 (wstat 768, 0x300)
Failed 3/3 subtests 
/home/local/convos/script/../t/web-base-url.t ................... ok    
/home/local/convos/script/../t/web-basic.t ...................... ok    
/home/local/convos/script/../t/web-connection-rooms.t ........... 1/? [superman@example.com/irc-localhost] connect(localhost:3123) == Verbindungsaufbau abgelehnt
/home/local/convos/script/../t/web-connection-rooms.t ........... ok    
/home/local/convos/script/../t/web-connections.t ................ 1/? [superman@example.com/irc-example] connect(irc.example.com:6667) == Can't connect: Der Name oder der Dienst ist nicht bekannt
[superman@example.com/irc-localhost] connect(localhost:36771) == SSL connect attempt failed error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol

/home/local/convos/script/../t/web-connections.t ................ ok    
/home/local/convos/script/../t/web-custom-assets.t .............. # 
/home/local/convos/script/../t/web-custom-assets.t .............. ok   
/home/local/convos/script/../t/web-dialog.t ..................... ok    
/home/local/convos/script/../t/web-embed.t ...................... ok    
/home/local/convos/script/../t/web-forced-server.t .............. 1/? [superman@example.com/irc-example] connect(chat.example.com:1234) == Can't connect: Der Name oder der Dienst ist nicht bekannt
/home/local/convos/script/../t/web-forced-server.t .............. ok    
/home/local/convos/script/../t/web-invite-code.t ................ ok    
/home/local/convos/script/../t/web-irc-events.t ................. ok     
/home/local/convos/script/../t/web-irc-highlight.t .............. ok    
/home/local/convos/script/../t/web-irc-msg.t .................... ok    
/home/local/convos/script/../t/web-login.t ...................... ok    
/home/local/convos/script/../t/web-recovery.t ................... ok    
/home/local/convos/script/../t/web-user.t ....................... ok    

Test Summary Report
-------------------
/home/local/convos/script/../t/config.t                       (Wstat: 256 Tests: 30 Failed: 1)
  Failed test:  8
  Non-zero exit status: 1
/home/local/convos/script/../t/version.t                      (Wstat: 768 Tests: 3 Failed: 3)
  Failed tests:  1-3
  Non-zero exit status: 3
/home/local/convos/script/../t/web-irc-events.t               (Wstat: 0 Tests: 103 Failed: 0)
  TODO passed:   86-87
Files=44, Tests=811, 37 wallclock secs ( 0.35 usr  0.27 sys + 32.55 cusr  2.38 csys = 35.55 CPU)
Result: FAIL
Failed 2/44 test programs. 4/811 subtests failed.

etchbox:/home/local/convos# TEST_SELENIUM=1 ./script/convos test t/selenium-*t
[Thu May 11 16:42:44 2017] [info] CONVOS_HOME="/root/.local/share/convos" # https://convos.by/doc/config.html#convos_home"
[Thu May 11 16:42:44 2017] [info] CONVOS_INVITE_CODE="2953e94daa75a4fc00d2f2bf7563f750" # https://convos.by/doc/config.html#convos_invite_code
t/selenium-basic.t ................. skipped: Could not connect to SeleniumWebDriver: Can't locate object method "flatten" via package "HTTP::Headers" at /home/local/convos/script/../local/lib/perl5/Test/Mojo/Role/Selenium.pm line 403.
t/selenium-hide.t .................. skipped: Could not connect to SeleniumWebDriver: Can't locate object method "flatten" via package "HTTP::Headers" at /home/local/convos/script/../local/lib/perl5/Test/Mojo/Role/Selenium.pm line 403.
t/selenium-highlight.t ............. skipped: Could not connect to SeleniumWebDriver: Can't locate object method "flatten" via package "HTTP::Headers" at /home/local/convos/script/../local/lib/perl5/Test/Mojo/Role/Selenium.pm line 403.
t/selenium-nick-change.t ........... skipped: Could not connect to SeleniumWebDriver: Can't locate object method "flatten" via package "HTTP::Headers" at /home/local/convos/script/../local/lib/perl5/Test/Mojo/Role/Selenium.pm line 403.
t/selenium-register-forced.t ....... skipped: Could not connect to SeleniumWebDriver: Can't locate object method "flatten" via package "HTTP::Headers" at /home/local/convos/script/../local/lib/perl5/Test/Mojo/Role/Selenium.pm line 403.
t/selenium-register-non-default.t .. skipped: Could not connect to SeleniumWebDriver: Can't locate object method "flatten" via package "HTTP::Headers" at /home/local/convos/script/../local/lib/perl5/Test/Mojo/Role/Selenium.pm line 403.
t/selenium-register.t .............. skipped: Could not connect to SeleniumWebDriver: Can't locate object method "flatten" via package "HTTP::Headers" at /home/local/convos/script/../local/lib/perl5/Test/Mojo/Role/Selenium.pm line 403.
t/selenium-responsive.t ............ skipped: Could not connect to SeleniumWebDriver: Can't locate object method "flatten" via package "HTTP::Headers" at /home/local/convos/script/../local/lib/perl5/Test/Mojo/Role/Selenium.pm line 403.
t/selenium-settings.t .............. skipped: Could not connect to SeleniumWebDriver: Can't locate object method "flatten" via package "HTTP::Headers" at /home/local/convos/script/../local/lib/perl5/Test/Mojo/Role/Selenium.pm line 403.
t/selenium-url.t ................... skipped: Could not connect to SeleniumWebDriver: Can't locate object method "flatten" via package "HTTP::Headers" at /home/local/convos/script/../local/lib/perl5/Test/Mojo/Role/Selenium.pm line 403.
Files=10, Tests=0, 21 wallclock secs ( 0.10 usr  0.04 sys + 10.33 cusr  0.87 csys = 11.34 CPU)
Result: NOTESTS

etchbox:/home/local/convos# TEST_SELENIUM=1 ./script/convos test t/selenium-settings.t
[Thu May 11 16:43:17 2017] [info] CONVOS_HOME="/root/.local/share/convos" # https://convos.by/doc/config.html#convos_home"
[Thu May 11 16:43:17 2017] [info] CONVOS_INVITE_CODE="2953e94daa75a4fc00d2f2bf7563f750" # https://convos.by/doc/config.html#convos_invite_code
t/selenium-settings.t .. skipped: Could not connect to SeleniumWebDriver: Can't locate object method "flatten" via package "HTTP::Headers" at /home/local/convos/script/../local/lib/perl5/Test/Mojo/Role/Selenium.pm line 403.
Files=1, Tests=0,  2 wallclock secs ( 0.02 usr  0.01 sys +  0.97 cusr  0.06 csys =  1.06 CPU)

etchbox:/home/local/convos# git show --oneline -s HEAD
310b43b Add Test::Mojo::Role::Selenium to cpanfile
</pre>

**Comment by jhthorsen** [comment]
"Could not connect to SeleniumWebDriver".. Did you install the chromdriver?

**Comment by ukcb** [comment]
<pre>
etchbox:~# dpkg -l chromedriver
ii  chromedriver   57.0.2987.98-1~deb8u i386
</pre>

I have set a link` ln -s /usr/lib/chromium/chromedriver /usr/bin/chromedriver`

**Comment by ukcb** [comment]
Do I need an X server for testing? My server is only accessible via SSH via console.

**Comment by jhthorsen** [comment]
Ah! I see... then it probably fails, because "chromdriver" need a monitor/screen.

**Comment by ukcb** [comment]
I can start chromium over ssh -X, but it does not change the test. I would have to build a completely new test environment. This does not happen quickly.

**Comment by ukcb** [comment]
Regardless of all tests, you should ensure that the Username is never empty; there is no input check. If only the Username is changed there is obviously no problem when saving. Maybe a default username (eg user, guest, etc.) would be necessary.
